OVERLAY_NAME := treble-overlay-samsung-r3q

LOCAL_PATH := .
include $(CLEAR_VARS)

LOCAL_MODULE := $(OVERLAY_NAME)
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_PATH := $(TARGET_OUT_PRODUCT)/overlay
LOCAL_SRC_FILES := $(OVERLAY_NAME).apk
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_CERTIFICATE := platform
LOCAL_MODULE_OWNER := samsung
LOCAL_DEX_PREOPT := false

include $(BUILD_PREBUILT)
